package(default_visibility = ["//visibility:public"])

cc_library(
    name = "macro",
    hdrs = glob(["include/**/*"]),
    strip_include_prefix = "include",
    include_prefix = "macro",
    alwayslink = True,
)
