cc_test(
    name = "segment_tree_test",
    srcs = ["segment_tree_test.cpp"],
    deps = [
        "//sdk:algorithm_v1",
        "@glog//:glog",
        "@googletest//:gtest_main",
    ],
    size="small",
)

cc_test(
    name = "ringbuffer_test",
    srcs = ["ringbuffer_test.cpp"],
    deps = [
        "//sdk:algorithm_v1",
        "@glog//:glog",
        "@googletest//:gtest_main",
    ],
    size="small",
)