cc_test(
    name = "segment_tree_test",
    srcs = ["segment_tree_test.cpp"],
    deps = [
        "//algorithm_v1:algorithm_v1",
        "@com_github_google_glog//:glog",
        "@com_google_googletest//:gtest_main",
    ],
)